variable "ami" {}
variable "instance_type" {}
variable "public_subnet_az1_id" {}
variable "sg_allow_tls_id" {}
variable "private_app_subnet_az1_id" {}
variable "public_subnet_az2_id" {}
variable "sg_allow_http_id" {}
variable "vpc_id" {}
variable "efs_dns_name" {}
variable "efs_mount_target" {}
variable "efs_mount_2_target" {}